_wandb:
    value:
        cli_version: 0.22.2
        e:
            6kkybhpw1y5meoop7q1xgnujkwjqvrt1:
                codePath: scripts/models/unet3d.py
                codePathLocal: scripts/models/unet3d.py
                cpu_count: 16
                cpu_count_logical: 22
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1005867986944"
                        used: "509018124288"
                email: simon.baur1992@gmail.com
                executable: /home/boeke/Desktop/lidc_project/lidc-env/bin/python
                git:
                    commit: bdfc87c5aa4ed97c1ca5af866f4b96513d6f8c14
                    remote: git@github.com:nikeboke/lidc_project.git
                gpu: NVIDIA RTX 3000 Ada Generation Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4608
                      memoryTotal: "8585740288"
                      name: NVIDIA RTX 3000 Ada Generation Laptop GPU
                      uuid: GPU-38df5557-9e8a-ad46-11af-49d984fd3e53
                host: gczwb54
                memory:
                    total: "33066729472"
                os: Linux-6.14.0-29-generic-x86_64-with-glibc2.39
                program: /home/boeke/Desktop/lidc_project/scripts/models/unet3d.py
                python: CPython 3.12.3
                root: /home/boeke/Desktop/lidc_project
                startedAt: "2025-10-22T20:19:10.361724Z"
                writerId: 6kkybhpw1y5meoop7q1xgnujkwjqvrt1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.22.2
            "12": 0.22.2
            "13": linux-x86_64
agg:
    value: soft
epochs:
    value: 20
lr:
    value: 0.001
